apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: projection-web

resources:
  - configmap-http-redirect.yaml
  - deployment.yaml
  - service.yaml
  - cronjob-wallet-health.yaml
  - cronjob-radar-positions.yaml
  - cronjob-radar-liquidations.yaml
  - cronjob-yields.yaml

images:
  - name: projection-web
    newName: projection-web
    newTag: latest
